### ISSUE TITLE
Feedback on `Google GenAI` Library - Conversation History

### ISSUE THREAD

**Issue by YoussefElsafi** [googleapis/python-genai#15]
Dear Google AI Team,

I am writing to provide feedback on the newly released `Google GenAI` library. I am an avid user of the `google.generativeai` library and was super excited to try out this new offering.

As a long-time user of `Google GenAI` having taken it out for a spin with its new features, it struck me that one very important feature for my application is seemingly missing: the keeping of conversation history. Specifically, in the `google.generativeai` library, this can be done via maintaining context across multiple turns of a conversation with:

```python
chat_session = model.start_chat(history=[.])
response = chat_session.send_message(".")
```

and access to history can be retrieved by:

```python
chat_session.history
```
The lack of such a clear history management of the conversation in `Google GenAI` is one of the most important limitations for the development of chatbot or conversational AI applications. Being able to keep track of-and use-past interactions is important to maintain context and assure coherence.

It's possible that the functionality is there and was overlooked in the documentation, or that there is another way to achieve similar functionality inside the library. If it is, I would be eternally grateful if someone could point me in that direction. Otherwise, if someone could confirm whether a feature for conversation history is going to be implemented in a future release of `Google GenAI`, that would also be great.

Thank you for your patience and consideration. I am eager to see further development in this promising library.

Best regards,

Youssef Elsafi

**Comment by jscud** [comment]
Great question, similar functionality is available in the chats module: https://googleapis.github.io/python-genai/genai.html#module-genai.chats Would this meet your needs?

**Comment by YoussefElsafi** [comment]
> Great question, similar functionality is available in the chats module: https://googleapis.github.io/python-genai/genai.html#module-genai.chats Would this meet your needs?

Thanks!

**Comment by BlindMaster24** [comment]
@YoussefElsafi Sorry for the dumb question, but how do I get the history in the end?

Interesting! Did you use Google API Core for error handling, or is error in genai enough? Sorry for the extra question.
