### ISSUE TITLE
How do I pass an image into generate_content_stream?

### ISSUE THREAD

**Issue by abi** [googleapis/python-genai#6]
More documentation and examples of the contents param in `generate_content_stream` would be helpful. I haven't managed to pass in a base64 image into contents yet.

**Comment by jscud** [comment]
We added some samples to the README today that might help. Is this the kind of example you're looking for? https://pypi.org/project/google-genai/

Also the Google AI forum might be another good place to ask questions like this: https://discuss.ai.google.dev/c/ai-studio/8

**Comment by abi** [comment]
Thanks @jscud The examples you've added are helpful. I'll give that a try.
